# Generated by Django 5.0.2 on 2024-03-01 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='location',
        ),
    ]
