# Generated by Django 5.0.2 on 2024-03-01 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_group_members_group_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='group_leader',
        ),
        migrations.AddField(
            model_name='trip',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.group'),
        ),
    ]
