# Generated by Django 5.0.2 on 2024-03-02 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_remove_trip_group_leader_trip_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='name',
        ),
    ]
