# Generated by Django 5.0.2 on 2024-03-04 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_remove_plan_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('date', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('day', models.CharField(max_length=10)),
            ],
        ),
    ]
