# Generated by Django 5.0.2 on 2024-03-04 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_holiday'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holiday',
            name='date',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
