# Generated by Django 5.0.2 on 2024-03-04 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_holiday_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
