# Generated by Django 5.0.2 on 2024-03-21 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_event_is_done'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.trip'),
        ),
    ]
