# Generated by Django 5.0.2 on 2024-03-22 08:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_student_group_student_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='group',
        ),
    ]
