# Generated by Django 5.0.2 on 2024-03-22 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_remove_student_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
