# Generated by Django 5.0.2 on 2024-03-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_trip_is_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='cost_split',
            field=models.BooleanField(default=False),
        ),
    ]
