# Generated by Django 5.0.2 on 2024-03-23 13:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_event_cost_split'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date', 'start_time']},
        ),
    ]
